version: "3.8"

services:
  refurbed-invoices:
    build: .
    restart: unless-stopped
    container_name: ${STACK_NAME}
    environment:
      - SHOP=${SHOP}
      - SHOPIFY_TOKEN=${SHOPIFY_TOKEN}
      - REFURBED_TOKEN=${REFURBED_TOKEN}
      - IMAP_SERVER=${IMAP_SERVER}
      - IMAP_USERNAME=${IMAP_USERNAME}
      - IMAP_PASSWORD=${IMAP_PASSWORD}
